import { ERROR_PREFIX } from "./constants.js";

const ERRORS_NAME = {
    USER:{
        STATUS_REQUIRED: `${ERROR_PREFIX}USER_STATUS_REQUIRED`,
        EMAIL_REQUIRED: `${ERROR_PREFIX}USER_EMAIL_REQUIRED`,
        FIRST_NAME_REQUIRED: `${ERROR_PREFIX}USER_FIRST_NAME_REQUIRED`,
        FIRST_NAME_LENGTH_INVALID: `${ERROR_PREFIX}USER_FIRST_NAME_LENGTH_INVALID`,
        LAST_NAME_REQUIRED: `${ERROR_PREFIX}USER_LAST_NAME_REQUIRED`,
        LAST_NAME_LENGTH_INVALID: `${ERROR_PREFIX}USER_LAST_NAME_LENGTH_INVALID`,
        EMAIL_INVALID: `${ERROR_PREFIX}USER_EMAIL_INVALID`,
        EMAIL_EXISTS: `${ERROR_PREFIX}USER_EMAIL_EXISTS`,
        PASSWORD_REQUIRED: `${ERROR_PREFIX}USER_PASSWORD_REQUIRED`,
    },
    TEAM:{
        NAME_EXISTS: `${ERROR_PREFIX}TEAM_NAME_EXISTS`,
        NAME_REQUIRED: `${ERROR_PREFIX}TEAM_NAME_REQUIRED`,
        NAME_LENGTH_INVALID: `${ERROR_PREFIX}TEAM_NAME_LENGTH_INVALID`,
        LOGO_REQUIRED: `${ERROR_PREFIX}TEAM_LOGO_REQUIRED`,
    }
};

const ERRORS_MESSAGE = {
    [ERRORS_NAME.TEAM.NAME_EXISTS]: "Team name already exists",
    [ERRORS_NAME.TEAM.NAME_REQUIRED]: "Team name is required",
    [ERRORS_NAME.TEAM.NAME_LENGTH_INVALID]: "Team name must be between 2 and 100 characters",
    [ERRORS_NAME.TEAM.LOGO_REQUIRED]: "Team logo is required",
    [ERRORS_NAME.USER.EMAIL_REQUIRED]: "Email is required",
    [ERRORS_NAME.USER.FIRST_NAME_REQUIRED]: "First name is required",
    [ERRORS_NAME.USER.FIRST_NAME_LENGTH_INVALID]: "First name must be between 2 and 100 characters",
    [ERRORS_NAME.USER.LAST_NAME_REQUIRED]: "Last name is required",
    [ERRORS_NAME.USER.LAST_NAME_LENGTH_INVALID]: "Last name must be between 2 and 100 characters",
    [ERRORS_NAME.USER.EMAIL_INVALID]: "Email is invalid",
    [ERRORS_NAME.USER.EMAIL_EXISTS]: "Email already exists",
    [ERRORS_NAME.USER.PASSWORD_REQUIRED]: "Password is required",
    [ERRORS_NAME.USER.STATUS_REQUIRED]: "Status is required",
};

export { ERRORS_NAME, ERRORS_MESSAGE };